# Generated by Django 5.2.14 on 2026-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('category', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/original/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
